#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : git-gui
Version  : 2.20.1
Release  : 1
URL      : https://www.kernel.org/pub/software/scm/git/git-2.20.1.tar.xz
Source0  : https://www.kernel.org/pub/software/scm/git/git-2.20.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 BSD-2-Clause BSL-1.0 GPL-2.0 MIT
Requires: git-gui-bin = %{version}-%{release}
Requires: git-gui-data = %{version}-%{release}
Requires: git-gui-libexec = %{version}-%{release}
Requires: git-gui-license = %{version}-%{release}
Requires: git-gui-locales = %{version}-%{release}
BuildRequires : asciidoc
BuildRequires : buildreq-golang
BuildRequires : curl-dev
BuildRequires : docbook-xml
BuildRequires : expat-dev
BuildRequires : libxml2-dev
BuildRequires : libxslt-bin
BuildRequires : nghttp2-dev
BuildRequires : openssl-dev
BuildRequires : pcre2-dev
BuildRequires : perl-Error
BuildRequires : python3-dev
BuildRequires : tcl
BuildRequires : tk
BuildRequires : util-linux
BuildRequires : xmlto
BuildRequires : zlib-dev

%description
git-jump
========
Git-jump is a script for helping you jump to "interesting" parts of your
project in your editor. It works by outputting a set of interesting
spots in the "quickfix" format, which editors like vim can use as a
queue of places to visit (this feature is usually used to jump to errors
produced by a compiler). For example, given a diff like this:

%package bin
Summary: bin components for the git-gui package.
Group: Binaries
Requires: git-gui-data = %{version}-%{release}
Requires: git-gui-libexec = %{version}-%{release}
Requires: git-gui-license = %{version}-%{release}

%description bin
bin components for the git-gui package.


%package data
Summary: data components for the git-gui package.
Group: Data

%description data
data components for the git-gui package.


%package libexec
Summary: libexec components for the git-gui package.
Group: Default
Requires: git-gui-license = %{version}-%{release}

%description libexec
libexec components for the git-gui package.


%package license
Summary: license components for the git-gui package.
Group: Default

%description license
license components for the git-gui package.


%package locales
Summary: locales components for the git-gui package.
Group: Default

%description locales
locales components for the git-gui package.


%prep
%setup -q -n git-2.20.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548337985
%configure --disable-static
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1548337985
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/git-gui
cp COPYING %{buildroot}/usr/share/package-licenses/git-gui/COPYING
cp compat/nedmalloc/License.txt %{buildroot}/usr/share/package-licenses/git-gui/compat_nedmalloc_License.txt
cp contrib/persistent-https/LICENSE %{buildroot}/usr/share/package-licenses/git-gui/contrib_persistent-https_LICENSE
cp contrib/subtree/COPYING %{buildroot}/usr/share/package-licenses/git-gui/contrib_subtree_COPYING
cp sha1dc/LICENSE.txt %{buildroot}/usr/share/package-licenses/git-gui/sha1dc_LICENSE.txt
cp t/diff-lib/COPYING %{buildroot}/usr/share/package-licenses/git-gui/t_diff-lib_COPYING
cp vcs-svn/LICENSE %{buildroot}/usr/share/package-licenses/git-gui/vcs-svn_LICENSE
%make_install
%find_lang git

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/git
%exclude /usr/bin/git-cvsserver
%exclude /usr/bin/git-receive-pack
%exclude /usr/bin/git-shell
%exclude /usr/bin/git-upload-archive
%exclude /usr/bin/git-upload-pack
%exclude /usr/bin/gitk

%files data
%defattr(-,root,root,-)
%exclude /usr/share/git-core/templates/description
%exclude /usr/share/git-core/templates/hooks/applypatch-msg.sample
%exclude /usr/share/git-core/templates/hooks/commit-msg.sample
%exclude /usr/share/git-core/templates/hooks/fsmonitor-watchman.sample
%exclude /usr/share/git-core/templates/hooks/post-update.sample
%exclude /usr/share/git-core/templates/hooks/pre-applypatch.sample
%exclude /usr/share/git-core/templates/hooks/pre-commit.sample
%exclude /usr/share/git-core/templates/hooks/pre-push.sample
%exclude /usr/share/git-core/templates/hooks/pre-rebase.sample
%exclude /usr/share/git-core/templates/hooks/pre-receive.sample
%exclude /usr/share/git-core/templates/hooks/prepare-commit-msg.sample
%exclude /usr/share/git-core/templates/hooks/update.sample
%exclude /usr/share/git-core/templates/info/exclude
%exclude /usr/share/git-gui/lib/about.tcl
%exclude /usr/share/git-gui/lib/blame.tcl
%exclude /usr/share/git-gui/lib/branch.tcl
%exclude /usr/share/git-gui/lib/branch_checkout.tcl
%exclude /usr/share/git-gui/lib/branch_create.tcl
%exclude /usr/share/git-gui/lib/branch_delete.tcl
%exclude /usr/share/git-gui/lib/branch_rename.tcl
%exclude /usr/share/git-gui/lib/browser.tcl
%exclude /usr/share/git-gui/lib/checkout_op.tcl
%exclude /usr/share/git-gui/lib/choose_font.tcl
%exclude /usr/share/git-gui/lib/choose_repository.tcl
%exclude /usr/share/git-gui/lib/choose_rev.tcl
%exclude /usr/share/git-gui/lib/class.tcl
%exclude /usr/share/git-gui/lib/commit.tcl
%exclude /usr/share/git-gui/lib/console.tcl
%exclude /usr/share/git-gui/lib/database.tcl
%exclude /usr/share/git-gui/lib/date.tcl
%exclude /usr/share/git-gui/lib/diff.tcl
%exclude /usr/share/git-gui/lib/encoding.tcl
%exclude /usr/share/git-gui/lib/error.tcl
%exclude /usr/share/git-gui/lib/git-gui.ico
%exclude /usr/share/git-gui/lib/index.tcl
%exclude /usr/share/git-gui/lib/line.tcl
%exclude /usr/share/git-gui/lib/logo.tcl
%exclude /usr/share/git-gui/lib/merge.tcl
%exclude /usr/share/git-gui/lib/mergetool.tcl
%exclude /usr/share/git-gui/lib/msgs/bg.msg
%exclude /usr/share/git-gui/lib/msgs/de.msg
%exclude /usr/share/git-gui/lib/msgs/el.msg
%exclude /usr/share/git-gui/lib/msgs/fr.msg
%exclude /usr/share/git-gui/lib/msgs/hu.msg
%exclude /usr/share/git-gui/lib/msgs/it.msg
%exclude /usr/share/git-gui/lib/msgs/ja.msg
%exclude /usr/share/git-gui/lib/msgs/nb.msg
%exclude /usr/share/git-gui/lib/msgs/pt_br.msg
%exclude /usr/share/git-gui/lib/msgs/pt_pt.msg
%exclude /usr/share/git-gui/lib/msgs/ru.msg
%exclude /usr/share/git-gui/lib/msgs/sv.msg
%exclude /usr/share/git-gui/lib/msgs/vi.msg
%exclude /usr/share/git-gui/lib/msgs/zh_cn.msg
%exclude /usr/share/git-gui/lib/option.tcl
%exclude /usr/share/git-gui/lib/remote.tcl
%exclude /usr/share/git-gui/lib/remote_add.tcl
%exclude /usr/share/git-gui/lib/remote_branch_delete.tcl
%exclude /usr/share/git-gui/lib/search.tcl
%exclude /usr/share/git-gui/lib/shortcut.tcl
%exclude /usr/share/git-gui/lib/spellcheck.tcl
%exclude /usr/share/git-gui/lib/sshkey.tcl
%exclude /usr/share/git-gui/lib/status_bar.tcl
%exclude /usr/share/git-gui/lib/tclIndex
%exclude /usr/share/git-gui/lib/themed.tcl
%exclude /usr/share/git-gui/lib/tools.tcl
%exclude /usr/share/git-gui/lib/tools_dlg.tcl
%exclude /usr/share/git-gui/lib/transport.tcl
%exclude /usr/share/git-gui/lib/win32.tcl
%exclude /usr/share/git-gui/lib/win32_shortcut.js
%exclude /usr/share/gitk/lib/msgs/bg.msg
%exclude /usr/share/gitk/lib/msgs/ca.msg
%exclude /usr/share/gitk/lib/msgs/de.msg
%exclude /usr/share/gitk/lib/msgs/es.msg
%exclude /usr/share/gitk/lib/msgs/fr.msg
%exclude /usr/share/gitk/lib/msgs/hu.msg
%exclude /usr/share/gitk/lib/msgs/it.msg
%exclude /usr/share/gitk/lib/msgs/ja.msg
%exclude /usr/share/gitk/lib/msgs/pt_br.msg
%exclude /usr/share/gitk/lib/msgs/ru.msg
%exclude /usr/share/gitk/lib/msgs/sv.msg
%exclude /usr/share/gitk/lib/msgs/vi.msg
%exclude /usr/share/gitweb/gitweb.cgi
%exclude /usr/share/gitweb/static/git-favicon.png
%exclude /usr/share/gitweb/static/git-logo.png
%exclude /usr/share/gitweb/static/gitweb.css
%exclude /usr/share/gitweb/static/gitweb.js
%exclude /usr/share/perl5/FromCPAN/Error.pm
%exclude /usr/share/perl5/FromCPAN/Mail/Address.pm
%exclude /usr/share/perl5/Git.pm
%exclude /usr/share/perl5/Git/I18N.pm
%exclude /usr/share/perl5/Git/IndexInfo.pm
%exclude /usr/share/perl5/Git/LoadCPAN.pm
%exclude /usr/share/perl5/Git/LoadCPAN/Error.pm
%exclude /usr/share/perl5/Git/LoadCPAN/Mail/Address.pm
%exclude /usr/share/perl5/Git/Packet.pm
%exclude /usr/share/perl5/Git/SVN.pm
%exclude /usr/share/perl5/Git/SVN/Editor.pm
%exclude /usr/share/perl5/Git/SVN/Fetcher.pm
%exclude /usr/share/perl5/Git/SVN/GlobSpec.pm
%exclude /usr/share/perl5/Git/SVN/Log.pm
%exclude /usr/share/perl5/Git/SVN/Memoize/YAML.pm
%exclude /usr/share/perl5/Git/SVN/Migration.pm
%exclude /usr/share/perl5/Git/SVN/Prompt.pm
%exclude /usr/share/perl5/Git/SVN/Ra.pm
%exclude /usr/share/perl5/Git/SVN/Utils.pm
/usr/share/gitk/lib/msgs/pt_pt.msg

%files libexec
%defattr(-,root,root,-)
%exclude /usr/libexec/git-core/git
%exclude /usr/libexec/git-core/git-add
%exclude /usr/libexec/git-core/git-add--interactive
%exclude /usr/libexec/git-core/git-am
%exclude /usr/libexec/git-core/git-annotate
%exclude /usr/libexec/git-core/git-apply
%exclude /usr/libexec/git-core/git-archimport
%exclude /usr/libexec/git-core/git-archive
%exclude /usr/libexec/git-core/git-bisect
%exclude /usr/libexec/git-core/git-bisect--helper
%exclude /usr/libexec/git-core/git-blame
%exclude /usr/libexec/git-core/git-branch
%exclude /usr/libexec/git-core/git-bundle
%exclude /usr/libexec/git-core/git-cat-file
%exclude /usr/libexec/git-core/git-check-attr
%exclude /usr/libexec/git-core/git-check-ignore
%exclude /usr/libexec/git-core/git-check-mailmap
%exclude /usr/libexec/git-core/git-check-ref-format
%exclude /usr/libexec/git-core/git-checkout
%exclude /usr/libexec/git-core/git-checkout-index
%exclude /usr/libexec/git-core/git-cherry
%exclude /usr/libexec/git-core/git-cherry-pick
%exclude /usr/libexec/git-core/git-citool
%exclude /usr/libexec/git-core/git-clean
%exclude /usr/libexec/git-core/git-clone
%exclude /usr/libexec/git-core/git-column
%exclude /usr/libexec/git-core/git-commit
%exclude /usr/libexec/git-core/git-commit-graph
%exclude /usr/libexec/git-core/git-commit-tree
%exclude /usr/libexec/git-core/git-config
%exclude /usr/libexec/git-core/git-count-objects
%exclude /usr/libexec/git-core/git-credential
%exclude /usr/libexec/git-core/git-credential-cache
%exclude /usr/libexec/git-core/git-credential-cache--daemon
%exclude /usr/libexec/git-core/git-credential-store
%exclude /usr/libexec/git-core/git-cvsexportcommit
%exclude /usr/libexec/git-core/git-cvsimport
%exclude /usr/libexec/git-core/git-cvsserver
%exclude /usr/libexec/git-core/git-daemon
%exclude /usr/libexec/git-core/git-describe
%exclude /usr/libexec/git-core/git-diff
%exclude /usr/libexec/git-core/git-diff-files
%exclude /usr/libexec/git-core/git-diff-index
%exclude /usr/libexec/git-core/git-diff-tree
%exclude /usr/libexec/git-core/git-difftool
%exclude /usr/libexec/git-core/git-difftool--helper
%exclude /usr/libexec/git-core/git-fast-export
%exclude /usr/libexec/git-core/git-fast-import
%exclude /usr/libexec/git-core/git-fetch
%exclude /usr/libexec/git-core/git-fetch-pack
%exclude /usr/libexec/git-core/git-filter-branch
%exclude /usr/libexec/git-core/git-fmt-merge-msg
%exclude /usr/libexec/git-core/git-for-each-ref
%exclude /usr/libexec/git-core/git-format-patch
%exclude /usr/libexec/git-core/git-fsck
%exclude /usr/libexec/git-core/git-fsck-objects
%exclude /usr/libexec/git-core/git-gc
%exclude /usr/libexec/git-core/git-get-tar-commit-id
%exclude /usr/libexec/git-core/git-grep
%exclude /usr/libexec/git-core/git-gui
%exclude /usr/libexec/git-core/git-gui--askpass
%exclude /usr/libexec/git-core/git-hash-object
%exclude /usr/libexec/git-core/git-help
%exclude /usr/libexec/git-core/git-http-backend
%exclude /usr/libexec/git-core/git-http-fetch
%exclude /usr/libexec/git-core/git-http-push
%exclude /usr/libexec/git-core/git-imap-send
%exclude /usr/libexec/git-core/git-index-pack
%exclude /usr/libexec/git-core/git-init
%exclude /usr/libexec/git-core/git-init-db
%exclude /usr/libexec/git-core/git-instaweb
%exclude /usr/libexec/git-core/git-interpret-trailers
%exclude /usr/libexec/git-core/git-legacy-rebase
%exclude /usr/libexec/git-core/git-log
%exclude /usr/libexec/git-core/git-ls-files
%exclude /usr/libexec/git-core/git-ls-remote
%exclude /usr/libexec/git-core/git-ls-tree
%exclude /usr/libexec/git-core/git-mailinfo
%exclude /usr/libexec/git-core/git-mailsplit
%exclude /usr/libexec/git-core/git-merge
%exclude /usr/libexec/git-core/git-merge-base
%exclude /usr/libexec/git-core/git-merge-file
%exclude /usr/libexec/git-core/git-merge-index
%exclude /usr/libexec/git-core/git-merge-octopus
%exclude /usr/libexec/git-core/git-merge-one-file
%exclude /usr/libexec/git-core/git-merge-ours
%exclude /usr/libexec/git-core/git-merge-recursive
%exclude /usr/libexec/git-core/git-merge-resolve
%exclude /usr/libexec/git-core/git-merge-subtree
%exclude /usr/libexec/git-core/git-merge-tree
%exclude /usr/libexec/git-core/git-mergetool
%exclude /usr/libexec/git-core/git-mergetool--lib
%exclude /usr/libexec/git-core/git-mktag
%exclude /usr/libexec/git-core/git-mktree
%exclude /usr/libexec/git-core/git-multi-pack-index
%exclude /usr/libexec/git-core/git-mv
%exclude /usr/libexec/git-core/git-name-rev
%exclude /usr/libexec/git-core/git-notes
%exclude /usr/libexec/git-core/git-p4
%exclude /usr/libexec/git-core/git-pack-objects
%exclude /usr/libexec/git-core/git-pack-redundant
%exclude /usr/libexec/git-core/git-pack-refs
%exclude /usr/libexec/git-core/git-parse-remote
%exclude /usr/libexec/git-core/git-patch-id
%exclude /usr/libexec/git-core/git-prune
%exclude /usr/libexec/git-core/git-prune-packed
%exclude /usr/libexec/git-core/git-pull
%exclude /usr/libexec/git-core/git-push
%exclude /usr/libexec/git-core/git-quiltimport
%exclude /usr/libexec/git-core/git-range-diff
%exclude /usr/libexec/git-core/git-read-tree
%exclude /usr/libexec/git-core/git-rebase
%exclude /usr/libexec/git-core/git-rebase--am
%exclude /usr/libexec/git-core/git-rebase--common
%exclude /usr/libexec/git-core/git-rebase--interactive
%exclude /usr/libexec/git-core/git-rebase--merge
%exclude /usr/libexec/git-core/git-rebase--preserve-merges
%exclude /usr/libexec/git-core/git-receive-pack
%exclude /usr/libexec/git-core/git-reflog
%exclude /usr/libexec/git-core/git-remote
%exclude /usr/libexec/git-core/git-remote-ext
%exclude /usr/libexec/git-core/git-remote-fd
%exclude /usr/libexec/git-core/git-remote-ftp
%exclude /usr/libexec/git-core/git-remote-ftps
%exclude /usr/libexec/git-core/git-remote-http
%exclude /usr/libexec/git-core/git-remote-https
%exclude /usr/libexec/git-core/git-remote-testsvn
%exclude /usr/libexec/git-core/git-repack
%exclude /usr/libexec/git-core/git-replace
%exclude /usr/libexec/git-core/git-request-pull
%exclude /usr/libexec/git-core/git-rerere
%exclude /usr/libexec/git-core/git-reset
%exclude /usr/libexec/git-core/git-rev-list
%exclude /usr/libexec/git-core/git-rev-parse
%exclude /usr/libexec/git-core/git-revert
%exclude /usr/libexec/git-core/git-rm
%exclude /usr/libexec/git-core/git-send-email
%exclude /usr/libexec/git-core/git-send-pack
%exclude /usr/libexec/git-core/git-serve
%exclude /usr/libexec/git-core/git-sh-i18n
%exclude /usr/libexec/git-core/git-sh-i18n--envsubst
%exclude /usr/libexec/git-core/git-sh-setup
%exclude /usr/libexec/git-core/git-shell
%exclude /usr/libexec/git-core/git-shortlog
%exclude /usr/libexec/git-core/git-show
%exclude /usr/libexec/git-core/git-show-branch
%exclude /usr/libexec/git-core/git-show-index
%exclude /usr/libexec/git-core/git-show-ref
%exclude /usr/libexec/git-core/git-stage
%exclude /usr/libexec/git-core/git-stash
%exclude /usr/libexec/git-core/git-status
%exclude /usr/libexec/git-core/git-stripspace
%exclude /usr/libexec/git-core/git-submodule
%exclude /usr/libexec/git-core/git-submodule--helper
%exclude /usr/libexec/git-core/git-svn
%exclude /usr/libexec/git-core/git-symbolic-ref
%exclude /usr/libexec/git-core/git-tag
%exclude /usr/libexec/git-core/git-unpack-file
%exclude /usr/libexec/git-core/git-unpack-objects
%exclude /usr/libexec/git-core/git-update-index
%exclude /usr/libexec/git-core/git-update-ref
%exclude /usr/libexec/git-core/git-update-server-info
%exclude /usr/libexec/git-core/git-upload-archive
%exclude /usr/libexec/git-core/git-upload-pack
%exclude /usr/libexec/git-core/git-var
%exclude /usr/libexec/git-core/git-verify-commit
%exclude /usr/libexec/git-core/git-verify-pack
%exclude /usr/libexec/git-core/git-verify-tag
%exclude /usr/libexec/git-core/git-web--browse
%exclude /usr/libexec/git-core/git-whatchanged
%exclude /usr/libexec/git-core/git-worktree
%exclude /usr/libexec/git-core/git-write-tree
%exclude /usr/libexec/git-core/mergetools/araxis
%exclude /usr/libexec/git-core/mergetools/bc
%exclude /usr/libexec/git-core/mergetools/bc3
%exclude /usr/libexec/git-core/mergetools/codecompare
%exclude /usr/libexec/git-core/mergetools/deltawalker
%exclude /usr/libexec/git-core/mergetools/diffmerge
%exclude /usr/libexec/git-core/mergetools/diffuse
%exclude /usr/libexec/git-core/mergetools/ecmerge
%exclude /usr/libexec/git-core/mergetools/emerge
%exclude /usr/libexec/git-core/mergetools/examdiff
%exclude /usr/libexec/git-core/mergetools/guiffy
%exclude /usr/libexec/git-core/mergetools/gvimdiff
%exclude /usr/libexec/git-core/mergetools/gvimdiff2
%exclude /usr/libexec/git-core/mergetools/gvimdiff3
%exclude /usr/libexec/git-core/mergetools/kdiff3
%exclude /usr/libexec/git-core/mergetools/kompare
%exclude /usr/libexec/git-core/mergetools/meld
%exclude /usr/libexec/git-core/mergetools/opendiff
%exclude /usr/libexec/git-core/mergetools/p4merge
%exclude /usr/libexec/git-core/mergetools/tkdiff
%exclude /usr/libexec/git-core/mergetools/tortoisemerge
%exclude /usr/libexec/git-core/mergetools/vimdiff
%exclude /usr/libexec/git-core/mergetools/vimdiff2
%exclude /usr/libexec/git-core/mergetools/vimdiff3
%exclude /usr/libexec/git-core/mergetools/winmerge
%exclude /usr/libexec/git-core/mergetools/xxdiff

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/git-gui/COPYING
/usr/share/package-licenses/git-gui/compat_nedmalloc_License.txt
/usr/share/package-licenses/git-gui/contrib_persistent-https_LICENSE
/usr/share/package-licenses/git-gui/contrib_subtree_COPYING
/usr/share/package-licenses/git-gui/sha1dc_LICENSE.txt
/usr/share/package-licenses/git-gui/t_diff-lib_COPYING
/usr/share/package-licenses/git-gui/vcs-svn_LICENSE

%files locales -f git.lang
%defattr(-,root,root,-)

